export enum EMinecraftStartScreenMessage {
	PARROTS_LOVE_COOKIES = "Parrots love cookies!",
	NOT_JUST_A_GAME = "Not just a game, it's an adventure!",
	MOMENTS_OF_DELIGHT = "Bringing you moments of delight for over 11 years.",
	PLACING_BLOCKS_AND_ADVENTURES = "A game about placing blocks and going on adventures.",
	GAME_THAT_CHANGED_EVERYTHING = "It's the game that changed everything.",
	MADE_WITH_LOVE = "Made with love by Jonas!",
	BUILD_A_SNOW_GOLEM = "Do you want to build a snow golem?",
	STAY_HYDRATED = "Remember to stay hydrated!",
	NOW_WITH_MORE_TURTLES = "Now with more turtles!",
	FUN_FOR_ALL_AGES = "Fun for all ages!",
	HOPE_YOURE_HAVING_FUN = "We hope you're having fun playing Minecraft!",
	MESSAGE_NEVER_APPEAR = "This message will never appear on the splash screen, isn't that weird?",
	MAKING_THE_WORLD_BLOCKIER = "Making the world a blockier place!",
	YAY_KITTENS = "Yay, kittens!",
	BROUGHT_BY_MOJANG = "Brought to you by Mojang Studios, but we're not at work right now.",
	NEVER_DIG_STRAIGHT_DOWN = "Never dig straight down!",
	INCREASE_YOUR_INTELLIGENCE = "Playing Minecraft can increase your intelligence!",
	MORE_FUN_THAN_TRADING = "More fun than Villager trading!",
	KEEPS_ON_GIVING = "The game that keeps on giving.",
	HAVE_FUN_TRANSLATION = "Woof! Woof! (translation: Have fun!)",
	DONT_FEED_CREEPERS = "Please don't feed the creepers.",
	ULTIMATE_DIGITAL_SANDBOX = "Minecraft: The ultimate digital sandbox.",
	BRICK_BY_BRICK = "Brick by brick!",
	SKYS_THE_LIMIT = "The sky's the limit!",
	ADVENTURE_IS_OUT_THERE = "Adventure is out there!",
	JUST_KEEP_MINING = "Just keep mining, just keep mining...",
}
